name: JASPAR-profile-inference
channels:
  - bioconda
  - conda-forge
  - insilichem
  - defaults
dependencies:
  - biopython=1.73
  - blast=2.9.0
  - gitpython=3.1.12
  - glmnet=2.1.1
  - hmmer=3.2.1
  - matplotlib=3.3.2
  - numpy=1.16.4
  - pandas=1.0.1
  - prody=1.10.8
  - pyparsing=2.4.2
  - python=3.6.11
  - python-coreapi=2.3.3
  - rsat-core=2020.02.29
  - seaborn=0.11.1
  - scipy=1.3.1
  - scikit-learn=0.21.3
  - tqdm=4.35.0 